=== matildecmp/CodificaTesti/tei.dtd
<!ELEMENT TEI (header, facsimile?, testo+, r1, r2)>

<!ELEMENT header (#PCDATA)>
<!ATTLIST header
          type CDATA "intestazione"
          lang NMTOKEN #IMPLIED>

<!ELEMENT facsimile (#PCDATA)>
<!ATTLIST facsimile
          source CDATA #REQUIRED
          ref IDREFS #IMPLIED>

<!ELEMENT testo (#PCDATA|seg)*>
<!ATTLIST testo
          id ID #REQUIRED
          type CDATA #IMPLIED>

<!ELEMENT seg (#PCDATA)>

<!ELEMENT r1 EMPTY>
<!ATTLIST r1
          id ID #REQUIRED>

<!ELEMENT r2 EMPTY>
<!ATTLIST r2
          id ID #REQUIRED>

=== matildecmp/CodificaTesti/dich_elem_e_attr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEI SYSTEM "tei.dtd">
<TEI>
    <header type="intestazione" lang="it"></header>
    <facsimile source="nomefile.jpg" ref="r1 r2"></facsimile>
    <testo id="t1" type="tipo1">
        <seg>Segmento di testo</seg>
    </testo>
    <testo id="t2"></testo>
    <r1 id="r1"></r1>
    <r2 id="r2"></r2>
</TEI>
